import { pipe2, pipe3, pipe4, pipe5, (|>) } from "./pipe"
import { fromList, fromArray } from "./sources"
import { map, tap } from "./operators"
import { forEach } from "./sinks"

/**
 * sources
 */
export fromList
export fromArray

/**
 * operators
 */
export map
export tap

/**
 * sinks
 */
export forEach

/**
 * convenience functions
 */
export pipe2
export pipe3
export pipe4
export pipe5
export (|>)
